# Generated by Django 5.2.17 on 2026-09-16 05:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(help_text='email | github | linkedin | resume', max_length=40)),
                ('label', models.CharField(max_length=40)),
                ('value', models.CharField(max_length=200)),
                ('href', models.CharField(max_length=500)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(blank=True, max_length=200)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('nav_name', models.CharField(max_length=120)),
                ('status_line', models.CharField(max_length=120)),
                ('watermark', models.CharField(max_length=40)),
                ('watermark_sub', models.CharField(max_length=40)),
                ('tagline', models.CharField(max_length=200)),
                ('hero_title_rows', models.JSONField(default=list)),
                ('currently_building_label', models.CharField(max_length=80)),
                ('currently_building', models.TextField()),
                ('open_to', models.CharField(max_length=80)),
                ('about_eyebrow', models.CharField(max_length=80)),
                ('about_title_html', models.CharField(max_length=255)),
                ('about_paragraphs', models.JSONField(default=list)),
                ('stats', models.JSONField(default=list)),
                ('skills_eyebrow', models.CharField(max_length=80)),
                ('skills_title_html', models.CharField(max_length=255)),
                ('skills_sub', models.TextField()),
                ('work_eyebrow', models.CharField(max_length=80)),
                ('work_title_html', models.CharField(max_length=255)),
                ('work_sub', models.TextField()),
                ('journey_eyebrow', models.CharField(max_length=80)),
                ('journey_title_html', models.CharField(max_length=255)),
                ('journey_sub', models.TextField()),
                ('contact_eyebrow', models.CharField(max_length=80)),
                ('contact_title_html', models.CharField(max_length=255)),
                ('contact_sub', models.TextField()),
                ('footer_tagline', models.TextField()),
                ('meta_title', models.CharField(max_length=200)),
                ('meta_description', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('github_url', models.URLField()),
                ('linkedin_url', models.URLField()),
                ('resume', models.FileField(blank=True, upload_to='resume/')),
                ('robot', models.FileField(blank=True, upload_to='robot/')),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profile',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('tags', models.JSONField(default=list)),
                ('url', models.CharField(blank=True, max_length=500)),
                ('bar_url', models.CharField(blank=True, max_length=200)),
                ('meta', models.CharField(max_length=80)),
                ('link_label', models.CharField(max_length=80)),
                ('badge', models.CharField(blank=True, max_length=80)),
                ('badge_variant', models.CharField(blank=True, help_text='art | default', max_length=20)),
                ('variant', models.CharField(blank=True, help_text='featured | dev', max_length=20)),
                ('lines', models.JSONField(default=list, help_text='e.g. ["wide","med","block","short","med"]')),
                ('hover', models.BooleanField(default=False)),
                ('preview', models.ImageField(blank=True, upload_to='previews/')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SkillCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=80)),
                ('icon', models.CharField(help_text='aiml | frontend | backend | tools', max_length=40)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Skill categories',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TechChip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=40)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TimelineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta', models.CharField(max_length=80)),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('order', models.PositiveIntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='portfolio.skillcategory')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
